name: Lint

on:
  - push
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Python dependencies
        run: |
          pip install black
      - uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.PAT }}
          black: true
          auto_fix: true

    
